# Generated by Django 4.2 on 2023-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweettype',
            name='schema_name',
            field=models.CharField(default='demo', max_length=100),
        ),
    ]
