# Generated by Django 4.2 on 2023-04-14 19:25

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_tenant', '0002_sweet_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweet',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
